'use strict';

exports.TOOLKITS = [
    {
        name:"sent",
        alias:"SE",
        fullname:"Tách câu",
        alltags:[
            {
                name:"BOS",
                cmd:"BOS"
            },
            {
                name:"EOS",
                cmd:"EOS"
            }
        ]
    },
    {
        name:"word",
        alias:"WS",
        fullname:"Tách từ",
        alltags:[
            {
                name:"B-W",
                cmd:"B-W"
            },
            {
                name:"I-W",
                cmd:"I-W"
            },
        ]
    },
    {
        name:"pos",
        alias:"PS",
        fullname:"Gắn nhãn",
        alltags:[
            {
                name:"N",
                cmd:"N"
            },
            {
                name:"V",
                cmd:"V"
            },
            {
                name:"R",
                cmd:"R"
            },
            {
                name:"M",
                cmd:"M"
            },
            {
                name:"CH",
                cmd:"CH"
            },
            {
                name:"C",
                cmd:"C"
            },
            {
                name:"A",
                cmd:"A"
            },
            {
                name:"E",
                cmd:"E"
            },
            {
                name:"P",
                cmd:"P"
            },
            {
                name:"Nu",
                cmd:"Nu"
            },
            {
                name:"Nc",
                cmd:"Nc"
            },
            {
                name:"L",
                cmd:"L"
            },
            {
                name:"Cc",
                cmd:"Cc"
            },
            {
                name:"X",
                cmd:"X"
            },
            {
                name:"Np",
                cmd:"Np"
            },
            {
                name:"T",
                cmd:"T"
            },
            {
                name:"Ny",
                cmd:"Ny"
            },
            {
                name:"Ni",
                cmd:"Ni"
            },
            {
                name:"Nb",
                cmd:"Nb"
            },
            {
                name:"Y",
                cmd:"Y"
            },
            {
                name:"Vb",
                cmd:"Vb"
            },
            {
                name:"I",
                cmd:"I"
            },
            {
                name:"Z",
                cmd:"Z"
            },
            {
                name:"B",
                cmd:"B"
            },
            {
                name:"Eb",
                cmd:"Eb"
            },
            {
                name:"Vy",
                cmd:"Vy"
            },
            {
                name:"Ab",
                cmd:"Ab"
            },
            {
                name:"Xy",
                cmd:"Xy"
            },
            {
                name:"Cb",
                cmd:"Cb"
            },
            {
                name:"Mb",
                cmd:"Mb"
            },
            {
                name:"Pb",
                cmd:"Pb"
            }
        ]
    },
    {
        name:"chunk",
        alias:"CK",
        fullname:"Nhóm từ",
        alltags:[
            {
                name:"B-NP",
                cmd:"B-NP"
            },
            {
                name:"B-VP",
                cmd:"B-VP"
            },
            {
                name:"B-AP",
                cmd:"B-AP"
            },
            {
                name:"B-PP",
                cmd:"B-PP"
            },
            {
                name:"I-NP",
                cmd:"I-NP"
            },
            {
                name:"I-AP",
                cmd:"I-AP"
            },
            {
                name:"I-VP",
                cmd:"I-VP"
            }
        ]
    },
    {
        name:"ner",
        alias:"NER",
        fullname:"Thực thể",
        alltags:[
            {
                name:"B-LOC",
                cmd:"B-LOC"
            },
            {
                name:"B-ORG",
                cmd:"B-ORG"
            },
            {
                name:"I-LOC",
                cmd:"I-LOC"
            },
            {
                name:"B-PER",
                cmd:"B-PER"
            },
            {
                name:"I-PER",
                cmd:"I-PER"
            },
            {
                name:"I-ORG",
                cmd:"I-ORG"
            },
            {
                name:"B-MISC",
                cmd:"B-MISC"
            },
            {
                name:"I-MISC",
                cmd:"I-MISC"
            }
        ]
    },
    {
        name:"sner",
        alias:"CHILD",
        fullname:"Thực thể con",
        alltags:[
            {
                name:"B-LOC",
                cmd:"B-LOC"
            },
            {
                name:"B-ORG",
                cmd:"B-ORG"
            },
            {
                name:"I-LOC",
                cmd:"I-LOC"
            },
            {
                name:"B-PER",
                cmd:"B-PER"
            },
            {
                name:"I-PER",
                cmd:"I-PER"
            },
            {
                name:"I-ORG",
                cmd:"I-ORG"
            },
            {
                name:"B-MISC",
                cmd:"B-MISC"
            },
            {
                name:"I-MISC",
                cmd:"I-MISC"
            }
        ]
    }
];
